---
title: "Carrera La Luz 2022 - Jonathan Montoya"
subtile: "Actividad 1 - Métodos y Simulación Estadística"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#96CDCD"
      fg: "#030303" 
      primary: "#BBFFFF" 
      base_font:
        google: Lobster
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(ggplot2)
library(paqueteMET)

data("CarreraLuz22")

  
Theme2 = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  # axis.text.y = element_blank(),
  axis.text = element_text( size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  
  strip.text = element_text(size=8),
  title =element_text(size=8, face='bold')
)# tamaño letra por grupos

# subsets-----------------------------------------------------------------------
CarreraLuz22$sex[CarreraLuz22$sex == "M"]="Hombre"
CarreraLuz22$sex[CarreraLuz22$sex == "F"]="Mujer"
#-------------------------------------------------------------------------------
CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Hombre")
CarreraLuz22F = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")

#-------------------------------------------------------------------------------
CarreraLuz22_c1M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="1. Juvenil")
CarreraLuz22_c2M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="2. Abierta")
CarreraLuz22_c3M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="3. Veteranos A")
CarreraLuz22_c4M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="4. Veteranos B")
CarreraLuz22_c5M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="5. Veteranos C")


CarreraLuz22_c1F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="1. Juvenil")
CarreraLuz22_c2F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="2. Abierta")
CarreraLuz22_c3F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="3. Veteranos A")
CarreraLuz22_c4F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="4. Veteranos B")
CarreraLuz22_c5F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="5. Veteranos C")
#-------------------------------------------------------------------------------

categoria= c("Juvenil","Abierta","Veteranos A", "Veteranos B","Veteranos C")
t2 = aggregate(CarreraLuz22$timerun/60, by=list(CarreraLuz22$categoria,CarreraLuz22$sex), FUN= summary)
t2=t2$x
t2m=t2[1:5,] 
row.names(t2m)=categoria
t2h=t2[6:10,] 
row.names(t2h)=categoria
```

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Distribución por Categorias
```{r}
paleta6=c("#00EEEE", "#4169E1", "#EE5C42", "#008B00", "#EEEE00", "#FFA54F")
# install.packages("dplyr")
# install.packages("scales")
library(dplyr)
# Transformación de los datos

v1 <- CarreraLuz22 %>% 
  group_by(categoria) %>% # Variable a ser transformada
  count() %>% 
  ungroup() %>% 
  mutate(pcnt = `n` / sum(`n`)) %>% 
  arrange(pcnt) %>%
  mutate(etiquetas = scales::percent(pcnt))

p2=ggplot(v1, aes(x="", y=pcnt, fill=categoria)) +
    geom_col() +
    scale_fill_manual(values=paleta6)+
    theme(panel.background = element_rect(fill = "#96CDCD"))+
    theme(plot.background = element_rect(fill = "#96CDCD"))+
    theme(plot.background = element_rect(color = "paleturquoise3", # Color del borde
                                        size = 5))+       # Ancho del borde
    theme(legend.background = element_rect(fill = "#96CDCD"))+
    geom_label(aes(label = etiquetas),
            position = position_dodge(width = 0.5), show.legend = FALSE ) +
    labs(title = " ",
        y= "Porcentajes por Categoria",
        x= "")+
    coord_polar(theta="y")
p2

```

### Hombre por categorías

```{r}
v2 <- CarreraLuz22M %>% 
  group_by(categoria) %>% # Variable a ser transformada
  count() %>% 
  ungroup() %>% 
  mutate(pcntm = `n` / sum(`n`)) %>% 
  arrange(pcntm) %>%
  mutate(etiquetasm = scales::percent(pcntm))
p3=ggplot(v2, aes(x="", y=pcntm, fill=categoria)) +
    geom_col() +
    scale_fill_manual(values=paleta6)+
    theme(panel.background = element_rect(fill = "#96CDCD"))+
    theme(plot.background = element_rect(fill = "#96CDCD"))+
    theme(plot.background = element_rect(color = "paleturquoise3", # Color del borde
                                        size = 5))+       # Ancho del borde
    theme(legend.background = element_rect(fill = "#96CDCD"))+
    geom_label(aes(label = etiquetasm),
            position = position_dodge(width = 0.5), show.legend = FALSE ) +
    labs(title = " ",
        y= "Porcentajes de Hombres por Categoria",
        x= "")+
    coord_polar(theta="y")
p3
```

### Mujeres por categoría
```{r}
v3 <- CarreraLuz22F %>% 
  group_by(categoria) %>% # Variable a ser transformada
  count() %>% 
  ungroup() %>% 
  mutate(pcntf = `n` / sum(`n`)) %>% 
  arrange(pcntf) %>%
  mutate(etiquetasf = scales::percent(pcntf))
p4=ggplot(v3, aes(x="", y=pcntf, fill=categoria)) +
    geom_col() +
    scale_fill_manual(values=paleta6)+
    theme(panel.background = element_rect(fill = "#96CDCD"))+
    theme(plot.background = element_rect(fill = "#96CDCD"))+
    theme(plot.background = element_rect(color = "paleturquoise3", # Color del borde
                                        size = 5))+       # Ancho del borde
    theme(legend.background = element_rect(fill = "#96CDCD"))+
    geom_label(aes(label = etiquetasf),
            position = position_dodge(width = 0.5), show.legend = FALSE ) +
    labs(title = " ",
        y= "Porcentajes de Mujeres por Categoria",
        x= "")+
    coord_polar(theta="y")
p4
```

### Más información

La siguiente tabla muestra la distribución de los rangos de tiempo respecto a los rangos de edad por cada sexo, se puede dar una lectura importante respecto a los hábitos de participación en este tipo de carreras por rangos de edad, por ejemplo en esta carrera se puede observar que las mujeres hasta los 34 años tuvieron una participación considerable respecto a otros rangos de edad, lo cual no sucede con los hombres que hasta los 37 años mostraron participación impportante.
Participación considerable llamamos al 50% del total de participación o Q2 por sexo.


```{r}
breaks=c(0,25,50,75,100,125,150,175)
breaks2=c(10,15,20,25,30,35,40,45,50,55,60,65,70,76)
Tiempo_Min=cut(CarreraLuz22$timerun/60,breaks)
Edad.corredores=cut(CarreraLuz22$edad,breaks2)
p5<-table(Edad.corredores,Tiempo_Min,CarreraLuz22$sex)
p5

```


Column {data-width=400}
-----------------------------------------------------------------------

### Rangos de edad por sexo

```{r}

ggplot(CarreraLuz22, aes(x = edad, fill = sex)) +
  geom_density(alpha = 0.5) +    
  labs(title = " ",
        y= "Frecuencia",
        x= "Edad")
```

### Rangos de tiempo por sexo

```{r}
ggplot(CarreraLuz22, aes(x = timerun/60, fill = sex)) +
  geom_density(alpha = 0.5) +    
  labs(title = " ",
        y= "Frecuencia",
        x= "Tiempo")
```

Column { data-width=50 }
-----------------------------------------------------------------------
### minimo  {.value-box}
```{r}
valueBox(value =paste(round(min(CarreraLuz22$timerun/60),1), "min"), 
         caption = "Tiempo ganador", 
         icon = "fa-thumbs-up", 
         color = "#0EB0C6")
```


### velocidad  {.value-box}
```{r}
valueBox(value =paste(round(10070/min(CarreraLuz22$timerun),2),"m/s"), # ud1$cierre, 
         caption = "Máxima velocidad", 
         icon = "fa-clock", 
         color = "#0EB0C6")
```


### distancia  {.value-box}
```{r}
valueBox(value = paste(10.07,"Km"), #ud1$min, 
         caption = "Distancia recorrida", 
         icon = "fa-solod fa-person-walking-arrow-right", 
         color = "#0EB0C6")
```


### volumen  {.value-box}
```{r}
valueBox(value = paste(length(CarreraLuz22$timerun),"atletas"), 
         caption = "Número de participantes", 
         icon = "fa-people", 
         color = "#0EB0C6")
```


### porcentaje  {.value-box}
```{r}
valueBox(value = paste(round(length(CarreraLuz22F$timerun)/length(CarreraLuz22$timerun)*100,2),"%"), 
         caption = "Porcentaje mujeres", 
         icon = "  ", 
         color = "#0EB0C6")
```

### promedio  {.value-box}
```{r}
valueBox(value = paste(round(mean(CarreraLuz22$timerun/60),2),"min"), 
         caption = "Tiempo promedio de carrera", 
         icon = "  ", 
         color = "#0EB0C6")
```
### Quantil Q2  {.value-box}
```{r}
valueBox(value = paste(round(quantile(CarreraLuz22$edad,0.5),1),"anios"),
         caption = "Cuantile Q2 de edad", 
         icon = "  ", 
         color = "#0EB0C6")
```

